#!/bin/bash
# DEBrowser 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    # Mount the parent project using dxFUSE
    wget https://github.com/dnanexus/dxfuse/releases/download/v0.21/dxfuse-linux
    chmod +x dxfuse-linux
    source environment >& /dev/null
    FUSE_MOUNT=$HOME/projects
    mkdir -p $FUSE_MOUNT
    sudo -E ./dxfuse-linux -uid $(id -u) -gid $(id -g) -verbose 2 $FUSE_MOUNT $DX_PROJECT_CONTEXT_ID
    PROJ_NAME=$(dx describe $DX_PROJECT_CONTEXT_ID --name)
    PROJ_PATH=${FUSE_MOUNT}/${PROJ_NAME}
    echo "Project ${PROJ_NAME} mounted as ${PROJ_PATH}"
    
    # Load docker image - this wont work if there are spaces in the project name
    docker load -i ${PROJ_PATH}/debrowser.docker.gz

    # Run the docker image. 
    docker run --rm  --name  debrowser -p 443:3838  -v $PROJ_PATH:/srv/project/ scoughlan/debrowser
}

